apiVersion: v2
name: o11y-control-plane
description: O11y OpAMP Control Plane with embedded React UI
type: application
version: 0.24.9
appVersion: "0.24.9"
kubeVersion: ">=1.28.0-0"
keywords:
  - opamp
  - opentelemetry
  - observability
annotations:
  artifacthub.io/license: Apache-2.0
